import assert from "node:assert/strict";
import { once } from "node:events";
import { readFile } from "node:fs/promises";
import { createServer, type Socket } from "node:net";
import { join } from "node:path";
import { createSecureContext, createServer as createTlsServer, TLSSocket } from "node:tls";
import { parseHeaderValue } from "nodemailer/lib/mime-funcs";

type Mode = "plain" | "starttls" | "tls";
export type FixtureMessage = {
  raw: string;
  from: string;
  recipients: string[];
  encrypted: boolean;
};

// This SMTP sink has no relay: every accepted message stays in this isolated test process.
export async function createSmtpFixture({
  mode,
  trusted = true,
  loginOnly = false,
}: {
  mode: Mode;
  trusted?: boolean;
  loginOnly?: boolean;
}) {
  assert.equal(process.env.MULTI_VENUE_ISOLATED_TEST, "true");
  const directory = process.env.SMTP_TEST_CERT_DIR;
  assert.ok(directory, "Test certificates must be generated by the isolated test runner");
  const certificate = trusted ? "trusted" : "untrusted";
  const credentials = {
    key: await readFile(join(directory, `${certificate}.key`)),
    cert: await readFile(join(directory, `${certificate}.crt`)),
  };
  const sockets = new Set<Socket>();
  const fixture = {
    accounts: new Map([["fixture@example.invalid", "fixture-smtp-password"]]),
    messages: [] as FixtureMessage[],
    authentications: [] as { method: string; encrypted: boolean; valid: boolean }[],
    rejection: null as "auth" | "recipient" | "data" | "disconnect" | null,
    beforeAccept: undefined as ((message: FixtureMessage) => Promise<void>) | undefined,
  };
  const attach = (initialSocket: Socket, initialEncryption: boolean, greeting = true) => {
    let socket = initialSocket;
    let encrypted = initialEncryption;
    let buffer = "";
    let authenticated = false;
    let loginStage = 0;
    let loginUser = "";
    let data = false;
    let raw = "";
    let from = "";
    let recipients: string[] = [];
    const track = (connection: Socket) => {
      sockets.add(connection);
      connection.on("close", () => sockets.delete(connection));
      connection.on("error", () => connection.destroy());
      connection.setTimeout(10000, () => connection.destroy());
      connection.setEncoding("utf8");
    };
    const authenticate = (method: string, user: string, password: string) => {
      const valid =
        fixture.accounts.has(user) &&
        fixture.accounts.get(user) === password &&
        fixture.rejection !== "auth";
      fixture.authentications.push({ method, encrypted, valid });
      authenticated = valid;
      socket.write(valid ? "235 Authenticated\r\n" : "535 Authentication failed\r\n");
    };
    const receive = (chunk: string) => {
      buffer += chunk;
      while (buffer.includes("\r\n")) {
        const index = buffer.indexOf("\r\n");
        const line = buffer.slice(0, index);
        buffer = buffer.slice(index + 2);
        if (data) {
          if (line !== ".") {
            raw += (line.startsWith("..") ? line.slice(1) : line) + "\r\n";
            continue;
          }
          data = false;
          const message = { raw, from, recipients: [...recipients], encrypted };
          raw = "";
          if (fixture.rejection === "data") socket.write("451 Test DATA refusal\r\n");
          else if (fixture.rejection === "disconnect") socket.destroy();
          else {
            void Promise.resolve(fixture.beforeAccept?.(message))
              .then(() => {
                fixture.messages.push(message);
                socket.write("250 Stored in test sink\r\n");
              })
              .catch(() => socket.destroy());
          }
        } else if (loginStage === 1) {
          loginUser = Buffer.from(line, "base64").toString("utf8");
          loginStage = 2;
          socket.write("334 UGFzc3dvcmQ6\r\n");
        } else if (loginStage === 2) {
          loginStage = 0;
          authenticate("LOGIN", loginUser, Buffer.from(line, "base64").toString("utf8"));
        } else if (/^(EHLO|HELO) /.test(line)) {
          socket.write(
            "250-fixture\r\n" +
              (mode === "starttls" && !encrypted
                ? "250 STARTTLS\r\n"
                : `250 AUTH ${loginOnly ? "LOGIN" : "PLAIN LOGIN"}\r\n`),
          );
        } else if (line === "STARTTLS" && mode === "starttls" && !encrypted) {
          socket.removeListener("data", receive);
          socket.write("220 Ready for TLS\r\n");
          socket = new TLSSocket(socket, {
            isServer: true,
            secureContext: createSecureContext(credentials),
          });
          encrypted = true;
          track(socket);
          socket.on("data", receive);
          return;
        } else if (line.startsWith("AUTH PLAIN ")) {
          const [, user, password] = Buffer.from(line.slice(11), "base64")
            .toString("utf8")
            .split("\0");
          authenticate("PLAIN", user, password);
        } else if (line === "AUTH LOGIN") {
          loginStage = 1;
          socket.write("334 VXNlcm5hbWU6\r\n");
        } else if (line.startsWith("MAIL FROM:")) {
          from = line.match(/<([^>]*)>/)?.[1] ?? "";
          recipients = [];
          socket.write(
            authenticated ? "250 Sender accepted\r\n" : "530 Authentication required\r\n",
          );
        } else if (line.startsWith("RCPT TO:")) {
          if (fixture.rejection === "recipient") socket.write("550 Test recipient refusal\r\n");
          else {
            recipients.push(line.match(/<([^>]*)>/)?.[1] ?? "");
            socket.write("250 Recipient accepted\r\n");
          }
        } else if (line === "DATA") {
          data = true;
          socket.write("354 Send data\r\n");
        } else if (line === "QUIT") socket.end("221 Bye\r\n");
        else socket.write("250 OK\r\n");
      }
    };
    track(socket);
    socket.on("data", receive);
    if (greeting) socket.write("220 Isolated SMTP fixture\r\n");
  };
  const server =
    mode === "tls"
      ? createTlsServer(credentials, (socket) => attach(socket, true))
      : createServer((socket) => attach(socket, false));
  server.on("tlsClientError", () => {});
  server.listen(mode === "tls" ? 465 : mode === "starttls" ? 587 : 0, "127.0.0.1");
  await once(server, "listening");
  const address = server.address();
  assert.ok(address && typeof address !== "string");
  return {
    state: fixture,
    port: address.port,
    async close() {
      for (const socket of sockets) socket.destroy();
      const closed = once(server, "close");
      server.close();
      await closed;
    },
  };
}

function decodeQuotedPrintable(value: string) {
  const unfolded = value.replace(/=\r\n/g, "");
  const bytes: number[] = [];
  for (let index = 0; index < unfolded.length; index++) {
    if (unfolded[index] === "=" && /^[0-9a-f]{2}$/i.test(unfolded.slice(index + 1, index + 3))) {
      bytes.push(parseInt(unfolded.slice(index + 1, index + 3), 16));
      index += 2;
    } else bytes.push(unfolded.charCodeAt(index));
  }
  return Buffer.from(bytes).toString("utf8");
}

// Decode only the UTF-8 MIME formats emitted by the app's Nodemailer test messages.
export function parseFixtureMessage(raw: string): {
  headers: Map<string, string>;
  parts: { type: string; text: string; disposition?: string }[];
} {
  const separator = raw.indexOf("\r\n\r\n");
  assert.ok(separator >= 0, "SMTP message must contain a MIME header/body separator");
  const headers = new Map(
    raw
      .slice(0, separator)
      .replace(/\r\n[\t ]+/g, " ")
      .split("\r\n")
      .map((line) => {
        const colon = line.indexOf(":");
        const value = line
          .slice(colon + 1)
          .trim()
          .replace(/\?=\s+(?==\?)/g, "?=")
          .replace(/=\?UTF-8\?([BQ])\?([^?]*)\?=/gi, (_, encoding: string, content: string) =>
            encoding.toUpperCase() === "B"
              ? Buffer.from(content, "base64").toString("utf8")
              : decodeQuotedPrintable(content.replace(/_/g, " ")),
          );
        return [line.slice(0, colon).toLowerCase(), value] as const;
      }),
  );
  const body = raw.slice(separator + 4);
  const contentType = parseHeaderValue(headers.get("content-type") ?? "text/plain");
  assert.equal(typeof contentType.value, "string");
  assert.ok(contentType.value);
  if (contentType.value.startsWith("multipart/")) {
    const boundary = contentType.params.boundary;
    assert.ok(boundary, "Multipart message must declare a boundary");
    return {
      headers,
      parts: body
        .split(`--${boundary}`)
        .slice(1)
        .filter((part) => !part.startsWith("--"))
        .flatMap((part) => parseFixtureMessage(part.replace(/^\r\n/, "")).parts),
    };
  }
  const encoding = headers.get("content-transfer-encoding");
  const text =
    encoding === "base64"
      ? Buffer.from(body, "base64").toString("utf8")
      : encoding === "quoted-printable"
        ? decodeQuotedPrintable(body)
        : body;
  return {
    headers,
    parts: [{ type: contentType.value, text, disposition: headers.get("content-disposition") }],
  };
}
